apiVersion: apps/v10
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: praj0404/argo_cd:${BUILD_NUMBER}
        ports:
        - containerPort: 80